# Generated by Django 5.2.2 on 2025-06-09 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('fundaciones', '0001_initial'),
        ('img_promocionales', '0001_initial'),
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicial', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('fundacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundaciones.fundacion')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img_promocionales.img_promocional')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.lugar')),
            ],
        ),
    ]
