# Generated by Django 5.2.2 on 2025-06-09 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_final',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_inicial',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicial',
            field=models.DateField(),
        ),
    ]
