# Generated by Django 5.2.2 on 2025-06-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mision', models.CharField(max_length=255)),
                ('areas_enfoque', models.CharField(max_length=255)),
                ('link_logo', models.CharField(max_length=255)),
                ('proyectos_destacados', models.CharField(max_length=255)),
            ],
        ),
    ]
